---
title: "This is"
date: 2018-06-20
---
title: This is 
author: Sparta
email: qadas@domain.com
description: > # this means to ignore newlines until "baseurl:"
  bla bla bla 

# social links
twitter_username: your-twitter-handle
github_username:  https://github.com/qumaksek

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
